feat(catalog): création d'un nouveau widget de consultation du catalogue de la GPF
IGNF/geopf-extensions-openlayers pull request #155
Opened 2024-08-23 08:55 UTC by lowzonenose

# Widget Catalog

> Afficher une liste des couches avec ou sans filtrage et avec ou sans catégorisation des données. La sélection d'une couche permet l'ajout sur la carte

## Interface 
![image](https://github.com/user-attachments/assets/831449ac-5aa5-46b9-8916-615abcb2f899)

## Options

```js
{
            title : "Gérer vos couches de données",
            layerLabel : "title",
            layerFilter : [],
            search : { 
                active : true, 
                criteria : [
                    "name",
                    "title",
                    "description"
                ]
            },
            addToMap : true,
            categories : [
                {
                    title : "Données",
                    filter : null
                }
            ],
            configuration : {
                mode : "internal",
                type : "json",
                urls : [
                    "https://raw.githubusercontent.com/IGNF/cartes.gouv.fr-entree-carto/main/public/data/layers.json",
                    "https://raw.githubusercontent.com/IGNF/cartes.gouv.fr-entree-carto/main/public/data/edito.json"
                ]
            },
}
```

Exemple : 
```js
var catalog = new ol.control.Catalog({
                        position: "top-left",
                        layerLabel : "name",
                        search : { 
                            active : true, 
                            criteria : [
                                "name"
                            ]
                        },
                        categories : [
                            {
                                title : "Fonds de carte",
                                filter : {
                                    field : "base",
                                    value : "true"
                                }
                            },
                            {
                                title : "Données",
                                items : [
                                    {
                                        title : "Thème",
                                        default : true,
                                        filter : {
                                            field : "thematic",
                                            value : "*"
                                        }
                                    },
                                    {
                                        title : "Producteur",
                                        filter : {
                                            field : "producer",
                                            value : "*"
                                        }
                                    },
                                    {
                                        title : "Autres",
                                        filter : null
                                    }
                                ]
                            }
                        ],
                        configuration : {
                            mode : "external",
                            type : "json",
                            data : data // objet json
                        }
});
map.addControl(catalog);
```
## Constituer le fichier json de configuration des couches

(?) question
> doit on internaliser ou l'externaliser la configuration ?

On peut mettre en place 2 modes: 

* internal

  Les json ou le service sont embarqués au widget, la constitution de la configuration est donc à la charge du widget.
  L'option de configuration ne sert donc qu'à surcharger le comportement.
  Le widget doit donc à son initialisation requêter soit les jsons, soit le service pour obtenir la configuration.
  Dans ce mode, on a plusieurs options pour surcharger le comportement :
    - choisir l'utilisation du service ou des jsons : `type`
    - surcharger les urls du service ou des jsons : `urls`

* external

  L'appel des json ou du service est completement à la charge du developpeur.
  Il doit construire le json d'entrée pour l'option de configuration.
  Dans ce mode, on a plusieurs options à renseigner :
    - choisir l'utilisation du service ou des jsons : `type`
    - fournir l'objet json : `data`
  Si on choisit le `type:json`, on doit fournir dans l'option `data`, le merge des jsons

(!) info
> La sortie json du service de recherche est surement differente que le json du portail avec son editorial.
> Donc, il faut mettre en place un mapping du service vers la conf.

2024-09-04 07:48 UTC, azarz requested changes
Changements à apporter aux samples spécifiques "catalog" : voir commentaires de review.

Sur le sample all modules, l'ajout du widget catalog empêche le chargement de tous les suivantes, avec en message d'erreur `DOMTokenList.add: The token can not contain whitespace.`
![image](https://github.com/user-attachments/assets/9d073754-2c68-442a-b171-f93afb05a130)
![image](https://github.com/user-attachments/assets/bd7a744a-b3f0-408d-95e1-0235f3e150dd)

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-categories-1.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-categories-1.html
> +            <h2>Ajout des outils de dessin</h2>
```suggestion
            <h2>Ajout du widget catalogue (catégories et filtres par mot clef)</h2>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-categories-2.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-categories-2.html
> +            <h2>Ajout des outils de dessin</h2>
```suggestion
            <h2>Ajout du widget catalogue (catégories et filtres par mot service)</h2>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-categories-3.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-categories-3.html
> +            <h2>Ajout des outils de dessin</h2>
```suggestion
            <h2>Ajout du widget catalogue (catégories par service)</h2>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-default.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-default.html
> +            <h2>Ajout des outils de dessin</h2>
Pas dessin + Préciser quelles options mises dans le widget catalog

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-filter.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-filter.html
> +            <h2>Ajout des outils de dessin</h2>
Pas dessin + Préciser quelles options mises dans le widget catalog

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-search.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-search.html
> +            <h2>Ajout des outils de dessin</h2>
Pas dessin + Préciser quelles options mises dans le widget catalog

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-type-data.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-type-data.html
> +            <h2>Ajout des outils de dessin</h2>
Pas dessin + Préciser quelles options mises dans le widget catalog

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-type-urls.html
> +        <title>Sample OpenLayers Drawing</title>
```suggestion
        <title>Sample OpenLayers Catalog</title>
```

2024-09-04 07:48 UTC, azarz commented on samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-type-urls.html
> +            <h2>Ajout des outils de dessin</h2>
Pas dessin + Préciser quelles options mises dans le widget catalog

2024-09-04 10:59 UTC, lowzonenose commented
> Changements à apporter aux samples spécifiques "catalog" : voir commentaires de review.
> 
> Sur le sample all modules, l'ajout du widget catalog empêche le chargement de tous les suivantes, avec en message d'erreur `DOMTokenList.add: The token can not contain whitespace.`
> 
> ![image](https://private-user-images.githubusercontent.com/18074428/364275237-9d073754-2c68-442a-b171-f93afb05a130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDU5NDksIm5iZiI6MTcyNTQ0NTY0OSwicGF0aCI6Ii8xODA3NDQyOC8zNjQyNzUyMzctOWQwNzM3NTQtMmM2OC00NDJhLWIxNzEtZjkzYWZiMDVhMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNWI0NDExYzAwYmVmZWRmMDYwY2JjNjgyZDg2NmNmOWJlYTA2NDBkZDI2OWE5ZjViMTI5YzBjODEzNDljM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TBE8NgCe9ioKURlEOhPh_2zR_95ZTArMLOR1f-oWOS8) ![image](https://private-user-images.githubusercontent.com/18074428/364275339-bd7a744a-b3f0-408d-95e1-0235f3e150dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDU5NDksIm5iZiI6MTcyNTQ0NTY0OSwicGF0aCI6Ii8xODA3NDQyOC8zNjQyNzUzMzktYmQ3YTc0NGEtYjNmMC00MDhkLTk1ZTEtMDIzNWYzZTE1MGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZWZiZjA4MzA2NDQ2MzliZGQ2NzQ4ODJmYTEzNTU1MjBhOTQxMTk2NDQyYTg0ZWE4M2U2ZWY5ODEzOTJjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqpZZAFEJb_QM_RMpVauyzp-2z_bocBXKeuGIF6SpME)

c'est l'overview qui semble mettre le bordel

2024-09-04 11:45 UTC, azarz approved these changes

2024-09-04 13:28 UTC, lowzonenose commented
TODOLIST
* [ ] déplacer les CSS inline dans un fichier
* [ ] implémenter l'appel au service de recherche
* [ ] mettre en place des filtres sur les couches à récupérer du json ou du service
* [ ] validation de la configuration à partir du schema
* [ ] mettre à jour la documentation utilisateur

++

* [ ] mettre en place ce widget pour le thème **classic**

2024-09-04 13:32 UTC, IGNFhc commented
Test des interactions avec le layer switcher :
Quand on supprime une couche depuis le layer switcher la case n'est pas décochée dans le catalog

2024-09-04 13:38 UTC, IGNFhc commented
![Capture d’écran du 2024-09-04 15-37-28](https://github.com/user-attachments/assets/9e7f2746-eeed-4dcc-9e17-61827d2fe2d6)
Les menus déroulants faudrait peut être laisser une petite marge entre la dernière couche et le titre de la prochaine section

2024-09-04 13:50 UTC, IGNFhc commented
![Capture d’écran du 2024-09-04 15-49-17](https://github.com/user-attachments/assets/aeddd2a3-76ec-46c6-bb03-d5189132c0a5)
Peut être une erreur de ma part 
si le fichier de conf est bien celui ci https://raw.githubusercontent.com/IGNF/cartes.gouv.fr-entree-carto/main/public/data/edito.json
on devrait avoir deux lignes dans la catégorie transport

2024-09-04 13:55 UTC, IGNFhc commented
![Capture d’écran du 2024-09-04 15-53-46](https://github.com/user-attachments/assets/ce791631-1eb0-4476-8ec5-b938462bbb19)
Ici on a 3 scrollbar beurk
est ce qu'on pourrait pas mettre au moins le nom des couches adapté à la taille de la largeur du menu ?

2024-09-05 13:00 UTC, azarz approved these changes
Reste juste le souci css des 3 scrollbars vu par Hector mais je n'ai pas trouvé de fix.

2024-09-06 13:29 UTC, merged