feat(gfi): pas d'affichage du tout si pas de données sous le clic
IGNF/geopf-extensions-openlayers pull request #301
Opened 2024-12-18 11:40 UTC by elias75015

Actuellement, s'il n'y a pas de données sous le clic (ou aucune layer), on affiche quand même la pop-up avec un message "Aucune données à Afficher".

Suite à quelques retours sur l'entrée carto, cette pop-up affchée par défaut peut sembler intempestive :

![image](https://github.com/user-attachments/assets/206f99dc-8e23-46f6-b016-ee0944b7576b)

Cette PR fait en sorte de ne rien afficher s'il n'y a pas de données ou pas de layer sous le clic lorsque le widget GFI est actif.

A challenger et en discuter avec PO.

2024-12-19 15:47 UTC, lowzonenose requested changes
il y'a un comportement bizarre quand il n'y a pas de données : 
* la popup s'ouvre avec une liste de couches
* puis, se referme aussitôt

Testé sur l'exemple : https://localhost:8080/samples/tests/GetFeatureInfo/pages-ol-getfeatureinfo-modules-options-dsfr.html

2024-12-19 18:07 UTC, elias75015 commented
Comportement déjà présent et non introduit par cette PR.
Ca semble lié à la mise à jour de l'accordéon DSFR

2024-12-20 12:52 UTC, elias75015 commented
On cache la pop-up et les entrées par défaut. Dans l'écouteur, on affiche la pop-up à partir ou du content est confirmé pour affichage

2024-12-20 16:11 UTC, elias75015 commented
On va dire que ça vous va

2024-12-24 13:43 UTC, merged